<a href="https://colab.research.google.com/github/Mintu-Vipin/Semester3/blob/master/MintuVipinJoy_COMP258Lab2_Ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as pl
from sklearn.preprocessing import LabelEncoder
%matplotlib inline

In [ ]:
# function to compute the sigmoid
sigmoid = lambda x: 1/(1 + np.exp(-x));
#
#function to comupute ReLU
def relu(z):
    return np.maximum(0,z)

def relu_derivative(z):
    return np.greater(z, 0).astype(int)

def softmax(z):
    z -= np.max(z)
    sm - (np.exp(z).T / np.sum(np.exp(z), axis=0)).T
    return sm

def softmax_grad(softmax):
    #Reshape the 1-d softwax to 2-d so that np.dot will do the matrix multiplication
    s=softmax.reshape(-1,1)
    return np.diagflat(s) - np.dot(s, s.T)   
    
################################################################################
# This function implements the backpropagation algorithm for a simple 4-5-3 ANN
#  W1 and W2 are the weight matrices of the respective layers:
#   W1 is the weight matrix between the input layer and hidden layer
#   W2 is the weight matrix between the hidden layer and output layer. 
#  X and D are the input and correct output of the training data (XOR), respectively.
################################################################################
def backprop(W1, W2, X, D):
    alpha = 0.01; # learning rate
    N=D.size;
    for k in range(0,N):
        x = X[k, :].T; #inputs from training data
        #print("x=",x)
        d = D[k]; # correct output from training data
        ##########################
        # forward propagation step
        ##########################
        # calculate the weighted sum of hidden node
        v1 = np.dot(W1,x);
        #print("v1= ", v1)
        #pass the weighted sum to the activation function, this gives the outputs from hidden layer
        y1 = sigmoid(v1);
        #print("y1= ", y1)
        #calculate the weighted sum of the output layer
        v = np.dot(W2,y1);
        #print("v", v)
        # pass it to the activation function, this returns the output of the third layer
        y = sigmoid(v);
        #y=softmax(v)
        #y=relu(v)
        #print("y=",y)
        #calculate the error, difference between correct output and computed output
        e = d - y;
        #print("e= ",e)
        #calculate delta, derivative of the activation function times the error
        # note that 𝜎′(𝑥)=𝜎(𝑥)∙(1− 𝜎(𝑥)) = y * (1-y)
        delta = y*(1-y)*e; # element wise multiplication
        #print("delta.shape= ",delta.shape)
        #print("delta", delta)
        ###########################
        # Backward propagation step
        ###########################
        # propagate the output node delta, δ, backward, and calculate the deltas of the hidden layer.
        e1 = np.dot(W2.T, delta);
        #print("e1= ",e1)
        delta1 = y1*(1-y1)*e1;  # element wise multiplication
        #print("relu derivative: = ",relu_derivative(y1))
        #relu_derivative =relu_derivative(y1)
        #relu_derivative.shape=(1,5)
        #delta1 = rlu_derivative*e1
        #print("delta1=",delta1)
        # Adjust the weights according to the learning rule
        #print("deta1.shape",delta1.shape)
        delta1.shape=(5,1) # column vector of deltas for the hidden layer
        x.shape=(1,4) # row vector of the current input
        dW1 = alpha*np.dot(delta1,x);
        W1 = W1 + dW1;
        #row vector of the hidden layer
        y1.shape = (1,5)
        delta.shape=(3,1)
        #print(y1.T.shape)
        dW2 = alpha*np.dot(delta,y1);
        W2 = W2 + dW2;
    #
    return W1, W2;
#

In [ ]:
# Training data

# Load the training data(Iris data)
iris_training = pd.read_json('training.json')
iris_training = pd.DataFrame(iris_training)
print("Iris training data\n-------------------\n",iris_training.head())
print("\n\nLength:  ",len(iris_training))
print("\n\nShape:   ",iris_training.shape)
print("\n\nInfo:\n   ",iris_training.info)
print("\n\nDescribe:\n   ",iris_training.describe())
print("\n\nHow many in each species:\n", iris_training['species'].value_counts())

# Extract output column
iris_y=iris_training['species']
print("\niris_y\n", iris_y)
en = LabelEncoder()
iris_y = en.fit_transform(iris_y)
# iris_y=np.array (iris_y.to_numpy ())
print("\niris_y\n",iris_y)
D=iris_y

# Input array

# Drop the class 'species'
iris_training.drop(['species'], axis = 1, inplace=True)
print (iris_training.head ())
iris_X=np.array(iris_training.to_numpy())
print("\niris_X\n",iris_X)
X=iris_X



# Testing data

# Load the testing data
iris_testing = pd.read_json('test.json')
iris_testing = pd.DataFrame(iris_testing)
print("Iris Testing data\n-------------------\n",iris_testing.head())
print("\n\nLength:  ",len(iris_testing))
print("\n\nShape:   ",iris_testing.shape)
print("\n\nInfo:\n   ",iris_testing.info)
print("\n\nDescribe:\n   ",iris_testing.describe())
print("\n\nHow many in each species:\n", iris_testing['species'].value_counts())


# Extract output column
iris_y_test=iris_testing['species']
print("\niris_y_test\n", iris_y_test)

# Input array

# Drop the class 'species'
iris_testing.drop(['species'], axis = 1, inplace=True)
print (iris_testing.head ())
iris_X_testing=np.array(iris_testing.to_numpy())
print("\niris_X_testing\n",iris_X_testing)

Iris training data
-------------------
    sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


Length:   147


Shape:    (147, 5)


Info:
    <bound method DataFrame.info of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
142         

In [ ]:
# initialize the weights between input layer and hidden layer
W1 = 2*np.random.rand(5, 4) - 1;

# initialize the weights between hidden layer and output layer
W2 = 2*np.random.rand(3, 5) - 1;

print("-----------------Before Updating weights:----------------")
print('Weight between input layer and hidden layer(W1) = \n', W1)
print('\nWeight between hidden layer and output layer(W2)= \n', W2)


# run the backprop algorithm to compute the weights
for epoch in range(1,10000): # train
    W1, W2 = backprop(W1, W2, X, D);
    
print("-----------------After Updating weights:----------------")
print('Weight between input layer and hidden layer(W1) = \n', W1)
print('\nWeight between hidden layer and output layer(W2)= \n', W2)



-----------------Before Updating weights:----------------
Weight between input layer and hidden layer(W1) = 
 [[-0.46871259  0.5995747   0.89548925  0.6814567 ]
 [ 0.66273405 -0.41258658  0.6257586  -0.60412873]
 [ 0.66406584 -0.77245103 -0.73540303  0.57390335]
 [ 0.2393468   0.1511916  -0.43077991  0.32699648]
 [-0.10358895  0.64504522 -0.32913563 -0.50852886]]

Weight between hidden layer and output layer(W2)= 
 [[ 0.27123308 -0.21299639 -0.15196204  0.19933963 -0.07841094]
 [ 0.29156355  0.76924601  0.03282275 -0.5973265  -0.78628635]
 [ 0.72060174  0.76464562 -0.5224536  -0.0511038  -0.09631703]]
-----------------After Updating weights:----------------
Weight between input layer and hidden layer(W1) = 
 [[-1.17231041 -0.67979093  2.3444527   1.42461296]
 [-0.30203625 -1.83296815  2.28849068  0.3206024 ]
 [ 1.08655497  0.21057655 -2.16650608 -0.16837023]
 [ 0.50451979  0.91713214 -1.77664319 -0.36147265]
 [ 0.28625415  1.50394594 -1.67447544 -1.18552081]]

Weight between hidden lay

In [ ]:
# Training

# calculate the output of the network with computed weights 
N = 147
for k in range(0,N):
    x = X[k, :].T; #inputs from training data
    
    ##########################
    # forward propagation step
    ##########################
    # calculate the weighted sum of hidden node
    v1 = np.dot(W1,x);
    #print("v1= ", v1)
    #pass the weighted sum to the activation function, this gives the outputs from hidden layer
    y1 = sigmoid(v1);
    #print("y1= ", y1)
    #calculate the weighted sum of the output layer
    v = np.dot(W2,y1);
    #print("v", v)
    # pass it to the activation function, this returns the output of the third layer
    y = sigmoid(v);
    print("y =",y)

y = [0.00506321 0.00504735 0.00501515]
y = [0.006184   0.00622891 0.00614186]
y = [0.00559123 0.0055741  0.00554818]
y = [0.00717424 0.00712707 0.00716585]
y = [0.00504291 0.00500926 0.00499778]
y = [0.00591761 0.00583804 0.00588334]
y = [0.0056074  0.00558274 0.00557067]
y = [0.00774925 0.00772751 0.0077406 ]
y = [0.00628203 0.00630032 0.00625934]
y = [0.00486159 0.0048473  0.00481163]
y = [0.00642376 0.00634009 0.00641271]
y = [0.00618568 0.00621567 0.0061557 ]
y = [0.00558651 0.00556435 0.00554616]
y = [0.00425508 0.00425186 0.00419173]
y = [0.00441473 0.00438863 0.00435709]
y = [0.00452726 0.00451246 0.00446683]
y = [0.00514042 0.0051242  0.00508887]
y = [0.00503097 0.00502027 0.00498185]
y = [0.00506771 0.00501715 0.00502334]
y = [0.00587888 0.00589377 0.00584566]
y = [0.00526061 0.0052147  0.00521217]
y = [0.00459782 0.00456921 0.00454251]
y = [0.00747583 0.00745994 0.0074286 ]
y = [0.00937206 0.00911178 0.00946922]
y = [0.00733723 0.00741577 0.00731974]
y = [0.00638762 0.0063439

In [ ]:
#Testing

# calculate the output of the network with computed weights 
N = 3
for k in range(0,N):
    x = iris_X_testing[k, :].T; #inputs from training data
    
    ##########################
    # forward propagation step
    ##########################
    # calculate the weighted sum of hidden node
    v1 = np.dot(W1,x);
    #print("v1= ", v1)
    #pass the weighted sum to the activation function, this gives the outputs from hidden layer
    y1 = sigmoid(v1);
    #print("y1= ", y1)
    #calculate the weighted sum of the output layer
    v = np.dot(W2,y1);
    #print("v", v)
    # pass it to the activation function, this returns the output of the third layer
    y = sigmoid(v);
    print("y =",y)



y = [0.0052765  0.00522372 0.00523317]
y = [0.99989454 0.99989417 0.99989483]
y = [0.99978294 0.99978199 0.99978304]
